from ml.sifts.data_integrity_sift import run_data_integrity_suite
from ml.sifts.train_test_sift import run_train_test_sift_suite
from ml.sifts.predictor_evaluation_sift import run_predictor_eval_suite
